import { renderToString } from 'react-dom/server.browser';
import { guide } from '../content/help';
import type { Env } from './auth';
export async function helpHtml(env:Env,request:Request){
 const asset=await env.ASSETS.fetch(new Request(new URL('/',request.url)));const shell=await asset.text();
 const styles=[...shell.matchAll(/<link\b[^>]*rel="stylesheet"[^>]*>/g)].map(match=>match[0]).join('');
 const body=renderToString(<><a className="help-skip" href="#help-main">Перейти к инструкции</a><header className="site-header help-header"><a className="brand" href="/"><span className="brand-symbol">N<span>ℓ</span></span><span><strong>{env.SITE_NAME}</strong><small>Терминология нейротехнологий</small></span></a><a className="button" href="/">Вернуться к словарю</a></header><div className="help-layout"><aside className="help-navigation"><details><summary>Содержание справки</summary><nav aria-label="Содержание справки">{guide.map(section=><a key={section.id} href={'#'+section.id}>{section.ru.title}</a>)}</nav></details></aside><main id="help-main" className="help-document"><div className="breadcrumb"><a href="/">Словарь</a> / Справка</div><h1>Как работать со словарём</h1><p className="help-intro">От поиска термина до собственной опубликованной карточки: пошаговые инструкции для читателя и автора.</p><nav className="help-shortcuts" aria-label="Быстрый переход"><a href="#create">Ввести карточку</a><a href="#files">Импортировать файл</a><a href="#feedback">Отправить отзыв</a></nav>{guide.map(section=><section id={section.id} key={section.id}><h2>{section.ru.title}<a className="help-anchor" href={'#'+section.id} aria-label={'Ссылка на раздел «'+section.ru.title+'»'}>#</a></h2>{section.ru.paragraphs.map((paragraph,index)=><p key={index}>{paragraph}</p>)}{section.ru.steps&&<ol>{section.ru.steps.map((step,index)=><li key={index}>{step}</li>)}</ol>}{section.ru.example&&<><h3>Пример CSV</h3><pre><code>{section.ru.example}</code></pre><p>Замените пример определения собственным текстом и добавьте источник после импорта.</p></>}</section>)}<footer className="help-footer"><h2>Дополнительные материалы</h2><p><a href="https://github.com/alexandr-panchenko/neurolex/blob/main/docs/USER-GUIDE.md">Инструкция в репозитории</a> · <a href="https://github.com/alexandr-panchenko/neurolex/blob/main/docs/INTEGRATION.md">HTTP API и MCP</a> · <a href="https://github.com/alexandr-panchenko/neurolex/blob/main/docs/SEMANTIC-PROFILE.md">Семантическая модель и проверка форматов</a></p><p><a href="https://www.w3.org/2016/04/ontolex/">OntoLex-Lemon</a> · <a href="https://www.w3.org/2019/09/lexicog/">Lexicog</a> · <a href="https://github.com/SciCrunch/NIF-Ontology">Источник NeuroLex/NIFSTD</a></p><a href="#help-main">К началу инструкции ↑</a></footer></main></div></>);
 return new Response('<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Справка — '+env.SITE_NAME.replaceAll('&','&amp;').replaceAll('<','&lt;')+'</title><meta name="description" content="Инструкция по поиску, вводу карточек, редактированию, импорту и публикации словарных статей.">'+styles+'</head><body>'+body+'</body></html>',{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}});
}
