import { DomainError, object, type DictionarySchema, type Document, type Json } from '../domain/model';
import { paragraph } from '../domain/mock';
const vocabulary='http://id.nlm.nih.gov/mesh/vocab#';
function literal(value:unknown):string{return typeof value==='string'?value:object(value)&&typeof value['@value']==='string'?value['@value']:'';}
async function get(id:string,fetcher:typeof fetch){if(!/^[DMT]\d{6,9}$/.test(id))throw new DomainError('INVALID_MESH_ID',422,'Укажите идентификатор MeSH, например D015225.');let response:Response;try{response=await fetcher('https://id.nlm.nih.gov/mesh/'+id+'.json',{signal:AbortSignal.timeout(15000),redirect:'manual'});}catch(e){throw new DomainError('SOURCE_UNAVAILABLE',502,'MeSH временно недоступен.',{reason:e instanceof Error?e.message.slice(0,200):'network error'});}if(!response.ok)throw new DomainError('SOURCE_ERROR',502,'Не удалось получить запись MeSH.',{status:response.status});const raw=await response.text();if(raw.length>100000)throw new DomainError('SOURCE_TOO_LARGE',422,'Внешняя запись слишком велика.');let data:unknown;try{data=JSON.parse(raw);}catch{throw new DomainError('SOURCE_FORMAT',502,'MeSH вернул ответ другого формата.',{contentType:response.headers.get('content-type')});}if(!object(data))throw new DomainError('SOURCE_FORMAT',502,'Неизвестный формат MeSH.');return data;}
export async function meshRecord(id:string,fetcher:typeof fetch=fetch){
 const descriptor=await get(id,fetcher);const concept=String(descriptor.preferredConcept||'');const match=concept.match(/^http:\/\/id\.nlm\.nih\.gov\/mesh\/(M\d{6,9})$/);if(!match)throw new DomainError('SOURCE_FORMAT',502,'В записи нет основного понятия.');const detail=await get(match[1]!,fetcher);
 const label=literal(descriptor.label||descriptor['http://www.w3.org/2000/01/rdf-schema#label']);const definition=literal(detail.scopeNote||detail[vocabulary+'scopeNote']);if(!label||!definition)throw new DomainError('SOURCE_INCOMPLETE',422,'В записи отсутствует термин или определение.');
 return {id,label,definition,descriptorUrl:'https://id.nlm.nih.gov/mesh/'+id,conceptUrl:concept,lastUpdated:descriptor.lastUpdated||null,retrievedAt:new Date().toISOString(),licenseUrl:'https://www.nlm.nih.gov/databases/download/terms_and_conditions_mesh.html'};
}
export function meshDocument(record:Awaited<ReturnType<typeof meshRecord>>,equivalent:string,schema:DictionarySchema):Document{
 const field=(predicate:string)=>schema.fields.find(f=>f.predicate===predicate||f.predicate.endsWith('#'+predicate));
 const term=field('http://www.w3.org/2000/01/rdf-schema#label');const definition=field('http://www.w3.org/2004/02/skos/core#definition');const russian=field('russianEquivalent');const sources=schema.fields.find(f=>f.type==='object'&&f.multiple&&f.predicate==='http://purl.org/dc/terms/source');
 if(!term||!definition||!russian||!sources||!equivalent.trim())throw new DomainError('IMPORT_MAPPING',422,'Для импорта нужны поля термина, русского эквивалента, определения и источников. Укажите русский эквивалент.');
 const source:Record<string,Json>={};for(const f of sources.fields||[]){if(f.predicate==='http://purl.org/dc/terms/identifier')source[f.id]='mesh-'+record.id;if(f.predicate==='http://purl.org/dc/terms/title')source[f.id]='NLM MeSH · '+record.label;if(f.predicate==='http://www.w3.org/2000/01/rdf-schema#seeAlso')source[f.id]=record.descriptorUrl;if(f.predicate==='http://purl.org/dc/terms/license')source[f.id]=record.licenseUrl;if(f.predicate.endsWith('#sourceNote'))source[f.id]='National Library of Medicine, MeSH RDF. Retrieved '+record.retrievedAt.slice(0,10)+'. Descriptor updated '+String(record.lastUpdated||'unknown')+'. English scope note reproduced from MeSH; Russian equivalent supplied by the author.';}
 return {id:record.label.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80),schemaVersion:schema.version,values:{[term.id]:record.label,[russian.id]:equivalent.trim(),[definition.id]:paragraph(record.definition) as unknown as Json,[sources.id]:[source],externalRecord:{provider:'NLM MeSH',id:record.id,descriptor:record.descriptorUrl,concept:record.conceptUrl,lastUpdated:String(record.lastUpdated||''),retrievedAt:record.retrievedAt,license:record.licenseUrl}}};
}
