import type { DictionarySchema, Field } from './model';
import { namespaces } from './export';
const iri=(v:string)=>'<'+v+'>';const lit=(v:string)=>JSON.stringify(v);
export function shacl(schema:DictionarySchema){
 const prefix=Object.entries({...namespaces,sh:'http://www.w3.org/ns/shacl#'}).map(([key,url])=>`@prefix ${key}: <${url}> .`).join('\n');
 const property=(f:Field):string=>{const constraints=[`sh:path ${iri(f.predicate)}`];if(f.required)constraints.push('sh:minCount 1');if(!f.multiple)constraints.push('sh:maxCount 1');switch(f.type){case 'object':constraints.push('sh:node [ '+(f.fields||[]).map((c)=>'sh:property [ '+property(c)+' ]').join(' ; ')+' ]');break;case 'reference':constraints.push('sh:nodeKind sh:IRI');break;case 'richText':constraints.push('sh:datatype rdf:langString');if(f.required)constraints.push('sh:minLength 1');break;case 'date':constraints.push('sh:datatype xsd:date');break;case 'number':constraints.push('sh:or ( [ sh:datatype xsd:integer ] [ sh:datatype xsd:double ] )');break;case 'boolean':constraints.push('sh:datatype xsd:boolean');break;default:constraints.push('sh:datatype xsd:string');if(f.required)constraints.push('sh:minLength 1','sh:pattern '+lit('\\S'));if(f.type==='enum')constraints.push('sh:in ( '+(f.options||[]).map(lit).join(' ')+' )');}return constraints.join(' ; ');};
 const fields=schema.fields.filter((f)=>!['term','equivalent','abbreviation','externalMappings'].includes(f.id));
 return prefix+'\n\n'+(['article','concept']as const).map((target)=>`[] a sh:NodeShape ; sh:targetClass ${target==='article'?'lexicog:Entry':'skos:Concept'} ; `+fields.filter((f)=>f.target===target).map((f)=>'sh:property [ '+property(f)+' ]').join(' ; ')+' .').join('\n')+'\n[] a sh:NodeShape ; sh:targetClass ontolex:LexicalEntry ; sh:property [ sh:path ontolex:canonicalForm ; sh:minCount 1 ; sh:maxCount 1 ; sh:nodeKind sh:IRI ] ; sh:property [ sh:path ontolex:sense ; sh:minCount 1 ; sh:class ontolex:LexicalSense ] .\n[] a sh:NodeShape ; sh:targetClass ontolex:Form ; sh:property [ sh:path ontolex:writtenRep ; sh:minCount 1 ; sh:datatype rdf:langString ; sh:minLength 1 ] .\n[] a sh:NodeShape ; sh:targetClass ontolex:LexicalSense ; sh:property [ sh:path ontolex:reference ; sh:minCount 1 ; sh:maxCount 1 ; sh:nodeKind sh:IRI ] ; sh:property [ sh:path ontolex:isSenseOf ; sh:minCount 1 ; sh:maxCount 1 ; sh:class ontolex:LexicalEntry ] .\n[] a sh:NodeShape ; sh:targetClass lexicog:UsageExample ; sh:property [ sh:path rdf:value ; sh:minCount 1 ; sh:datatype rdf:langString ; sh:minLength 1 ] .\n';
}
