import type { Field, Json } from '../domain/model';
import { text } from '../domain/export';
import { paragraph } from '../domain/mock';
import { SearchPicker } from './SearchPicker';
import { RichReading } from './RichText';
import { lazy, Suspense } from 'react';
const RichEditor = lazy(() => import('./RichEditor').then((m) => ({ default: m.RichEditor }))); 
export interface Choice { id: string; label: string; searchText?:string }
export function emptyValue(f: Field): Json { if(f.multiple)return []; switch(f.type){ case 'richText':return paragraph('');case 'object':return Object.fromEntries((f.fields||[]).filter((v)=>v.required).map((v)=>[v.id,emptyValue(v)]));case 'boolean':return false;case 'number':return 0;default:return ''; } }
export function ArticleField({ field:f, value, editing, change, terms, sources, path, categories = [], errors = [] }: { field:Field;value:Json|undefined;editing:boolean;change:(v:Json|undefined)=>void;terms:Choice[];sources:Choice[];path:string;errors?: string[];categories?:Choice[] }) {
  const props={editing,terms,sources,errors,categories};
  const nested=(field:Field,val:Json|undefined,set:(v:Json|undefined)=>void,at:string)=><ArticleField key={at} field={field} value={val} change={set} path={at} {...props}/>;
  if(f.multiple){ const items=Array.isArray(value)?value:[]; if(!editing && !items.length)return <p className="muted">Пока не заполнено.</p>; return <div className="repeated">{items.map((v,i)=><div className={f.id==='examples'?'example repeated-item':'repeated-item'} key={i} id={f.id==='sources' && v && typeof v==='object' && !Array.isArray(v)?'source-'+String(v.id):undefined}>{nested({...f,multiple:false},v,(next)=>change(items.map((item,j)=>j===i?(next??emptyValue({...f,multiple:false})):item)),`${path}/${i}`)}{editing&&<button type="button" className="text-button" onClick={()=>change(items.filter((_,j)=>j!==i))}>Удалить этот элемент</button>}</div>)}{editing&&<button type="button" className="button" onClick={()=>change([...items,f.id==='sources'?{...(emptyValue({...f,multiple:false}) as Record<string,Json>),id:'source-'+crypto.randomUUID().slice(0,8)}:emptyValue({...f,multiple:false})])}>Добавить: {f.label.toLocaleLowerCase()}</button>}</div>; }
  if(f.type==='object'){ const data=value && typeof value==='object' && !Array.isArray(value)?value:{};if(f.id==='sources'){const edit=(id:string)=>{const child=f.fields?.find(v=>v.id===id);return child?nested(child,data[id],v=>{const next={...data};if(v===undefined)delete next[id];else next[id]=v;change(next);},`${path}/${id}`):null;};return <div className="source-record">{editing?<div className="source-title">{edit('title')}</div>:<a href={String(data.url||'')} rel="noreferrer">{String(data.title||'Источник')}</a>}{editing?<div className="muted">{edit('note')}</div>:data.note&&<p className="muted">{String(data.note)}</p>}{editing?<details><summary>Ссылка и атрибуция источника</summary><span className="field-caption">URL источника</span>{edit('url')}<span className="field-caption">Лицензия, если известна</span>{edit('license')}</details>:data.license&&<p className="muted">Лицензия: {String(data.license)}</p>}{(f.fields||[]).filter((child)=>!['id','title','url','note','license'].includes(child.id)&&data[child.id]!==undefined).map((child)=>nested(child,data[child.id],v=>change({...data,[child.id]:v??''}),`${path}/${child.id}`))}</div>;}

  return <div className="group-fields">{!editing && data.evidence==='synthetic'&&<span className="example-label">СИНТЕТИЧЕСКИЙ УЧЕБНЫЙ ПРИМЕР</span>}{(f.fields||[]).filter((child)=>(child.required||data[child.id]!==undefined)&&!(f.id==='sources'&&child.id==='id')).map((child)=><div key={child.id} className="nested-field">{(editing||data[child.id]!==undefined)&&<span className="field-caption">{child.label}{editing&&child.required?' *':''}</span>}{nested(child,data[child.id],(v)=>{const next={...data};if(v===undefined)delete next[child.id];else next[child.id]=v;change(next);},`${path}/${child.id}`)}</div>)}{editing&&(f.fields||[]).some(child=>!child.required&&data[child.id]===undefined)&&<details><summary>Добавить сведения</summary>{(f.fields||[]).filter(child=>!child.required&&data[child.id]===undefined).map(child=><div className="nested-field" key={child.id}><span className="field-caption">{child.label}</span>{nested(child,undefined,v=>{if(v!==undefined)change({...data,[child.id]:v});},`${path}/${child.id}`)}</div>)}</details>}</div>; }
  const error=errors.some((p)=>p===path||p.startsWith(path+'/'));
  if(!editing){ if(value===undefined || value==='')return <span className="muted">Не указано</span>;if(f.type==='richText')return <RichReading value={value}/>;if(f.type==='reference'){const label=terms.find((t)=>t.id===value)?.label||String(value);return <a href={/^https?:/.test(String(value))?String(value):'/article/'+String(value)}>{label}</a>;}if(typeof value==='boolean')return <span>{value?'Да':'Нет'}</span>;return <span>{({synthetic:'Синтетический пример',attested:'Засвидетельствованный фрагмент',ru:'Русский',en:'Английский'} as Record<string,string>)[String(value)]||text(value)||String(value)}</span>; }
  let control;
  if(f.type==='richText') control=<Suspense fallback={<p>Загрузка редактора…</p>}><RichEditor label={f.label} value={value||paragraph('')} onChange={(v)=>change(v)} terms={terms} sources={sources}/></Suspense>;
  else if(f.id==='category')control=<SearchPicker label="Раздел словаря" value={typeof value==='string'?value:''} choices={categories} allowCreate change={change}/>;
  else if(f.type==='reference'&&f.target==='concept')control=<SearchPicker label={f.label} value={typeof value==='string'?value:''} choices={terms} change={change}/>;
  else if(f.type==='enum')control=<select aria-label={f.label} value={typeof value==='string'?value:''} onChange={(e)=>change(e.target.value||undefined)}><option value="">Выберите значение</option>{f.options?.map((o)=><option key={o}>{o}</option>)}</select>;
  else if(f.type==='boolean')control=<input type="checkbox" aria-label={f.label} checked={value===true} onChange={(e)=>change(e.target.checked)}/>;
  else control=<input aria-label={f.label} placeholder={f.id==='abbreviation'?'Аббревиатура':undefined} type={f.type==='number'?'number':f.type==='date'?'date':'text'} value={typeof value==='string'||typeof value==='number'?value:''} onChange={(e)=>change(e.target.value===''&&!f.required?undefined:f.type==='number'?Number(e.target.value):e.target.value)}/>;
  return <div className={'inline-control'+(error?' invalid':'')}>{control}{error&&<span className="field-error">Проверьте это значение.</span>}</div>;
}
