import { useState } from 'react';
import type { DictionarySchema, Document } from '../domain/model';
import { parseTable, tableDocuments } from '../domain/tabular';
import { text } from '../domain/export';
import { api } from './api';
type Outcome={id?:string;exists?:boolean;revision?:number;error?:string;details?:unknown;differences?:{field:string;current:unknown;incoming:unknown}[]};
export function ImportArticles({schema,done}:{schema:DictionarySchema;done:()=>Promise<unknown>}){
 const [meshId,setMeshId]=useState('');const [equivalent,setEquivalent]=useState('');
 const [table,setTable]=useState<ReturnType<typeof parseTable>|null>(null);const [mapping,setMapping]=useState<Record<string,string>>({});const [raw,setRaw]=useState('');const [documents,setDocuments]=useState<Document[]>([]);const [outcomes,setOutcomes]=useState<Outcome[]|null>(null);const [replace,setReplace]=useState<Record<string,string[]>>({});const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
 async function run(task:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await task();}catch(e){setError(e instanceof Error?e.message:'Импорт не выполнен.');}finally{setBusy(false);}}
 function reset(){setOutcomes(null);setReplace({});}
 return <section><h1>Импорт статей</h1><details><summary>Получить статью из NLM MeSH</summary><label className="field">Идентификатор MeSH<input value={meshId} onChange={e=>setMeshId(e.target.value)} placeholder="D015225"/></label><label className="field">Русский эквивалент<input value={equivalent} onChange={e=>setEquivalent(e.target.value)}/></label><button className="button" disabled={busy||!meshId||!equivalent} onClick={()=>void run(async()=>{const result=await api<{document:Document}>('/api/import/mesh',{id:meshId,equivalent});setRaw(JSON.stringify([result.document],null,2));setTable(null);reset();})}>Получить и проверить</button><p><a href="https://meshb.nlm.nih.gov/" target="_blank" rel="noopener noreferrer">Найти идентификатор в MeSH</a></p></details><p>Выберите файл и проверьте статьи перед добавлением. Они сохранятся как черновики.</p>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}<label className="field">Файл CSV или JSON<input type="file" accept=".csv,.tsv,.json,text/csv,application/json" onChange={e=>{const file=e.target.files?.[0];if(file)void run(async()=>{const content=await file.text();reset();if(/\.(csv|tsv)$/i.test(file.name)){const next=parseTable(content);setTable(next);setMapping(Object.fromEntries(next.headers.map(header=>[header,header==='id'?'@id':schema.fields.find(f=>f.id===header||f.label.toLowerCase()===header.toLowerCase())?.id||''])));setRaw('');}else{setRaw(content);setTable(null);}});}}/></label>
 {table?<><h2>Соответствие столбцов</h2>{table.headers.map(header=><label className="field" key={header}>{header}<select value={mapping[header]||''} onChange={e=>{setMapping({...mapping,[header]:e.target.value});reset();}}><option value="">Пропустить</option><option value="@id">Идентификатор статьи</option>{schema.fields.map(field=><option key={field.id} value={field.id}>{field.label}</option>)}</select><small>Пример: {table.rows[0]?.[table.headers.indexOf(header)]||'—'}</small></label>)}<p>Строк: {table.rows.length}. Для повторяемых простых значений используйте точку с запятой; для групп — JSON.</p></>:<label className="field">Документы JSON<textarea rows={12} value={raw} onChange={e=>{setRaw(e.target.value);reset();}}/></label>}
 <button className="button" disabled={busy} onClick={()=>void run(async()=>{const parsed=table?tableDocuments(table,mapping,schema):JSON.parse(raw) as {documents?:Document[]};const docs=Array.isArray(parsed)?parsed:parsed.documents;if(!Array.isArray(docs))throw new Error('Нужен массив статей или экспорт словаря.');setDocuments(docs);const preview=await api<{outcomes:Outcome[]}>('/api/import/preview',{documents:docs,schemaVersion:schema.version});setOutcomes(preview.outcomes);setReplace({});})}>Проверить импорт</button>
 {outcomes&&<><h2>Результат проверки</h2>{outcomes.map((outcome,index)=><article className="import-outcome" key={index}><h3>{outcome.id||'Строка '+(index+1)} · {outcome.error?'Ошибка':outcome.exists?'Существующая статья':'Новая статья'}</h3>{outcome.error?<pre>{JSON.stringify(outcome.details,null,2)}</pre>:outcome.differences?.map(diff=><div className="import-difference" key={diff.field}><strong>{schema.fields.find(f=>f.id===diff.field)?.label||diff.field}</strong>{outcome.exists&&<p>Сейчас: {text(diff.current as never)||'—'}</p>}<p>Из файла: {text(diff.incoming as never)||'—'}</p>{outcome.exists&&diff.current!==null&&<label><input type="checkbox" checked={replace[outcome.id!]?.includes(diff.field)||false} onChange={e=>setReplace({...replace,[outcome.id!]:e.target.checked?[...(replace[outcome.id!]||[]),diff.field]:(replace[outcome.id!]||[]).filter(f=>f!==diff.field)})}/> Заменить это поле</label>}</div>)}</article>)}<button className="button primary" disabled={busy||outcomes.some(o=>o.error)||!documents.length} onClick={()=>void run(async()=>{await api('/api/import/apply',{documents,schemaVersion:schema.version,replaceFields:replace,expectedRevisions:Object.fromEntries(outcomes.filter(o=>o.id).map(o=>[o.id,o.revision]))},'POST',crypto.randomUUID());await done();setNotice('Статьи сохранены в черновиках.');setOutcomes(null);})}>Импортировать черновики</button></>}
 <p><a href="/api/export?private=1" download>Экспорт словаря</a></p></section>;
}
