import { useId, useState } from 'react';
import type { Choice } from './ArticleField';
export function SearchPicker({label,value,choices,change,allowCreate=false}:{label:string;value:string;choices:Choice[];change:(value:string|undefined)=>void;allowCreate?:boolean}){
 const id=useId();const selected=choices.find(c=>c.id===value)?.label||value;const [query,setQuery]=useState<string|null>(null);const [open,setOpen]=useState(false);const [active,setActive]=useState(0);
 const input=query??selected;const normalized=(query??'').trim().toLocaleLowerCase();const results=choices.filter(c=>!normalized||(c.label+' '+c.id+' '+(c.searchText||'')).toLocaleLowerCase().includes(normalized)).slice(0,12);const create=allowCreate&&!!normalized&&!choices.some(c=>c.id.toLocaleLowerCase()===normalized);
 function choose(next:string){change(next);setQuery(null);setOpen(false);setActive(0);}
 const count=results.length+(create?1:0);
 return <div className="search-picker"><input role="combobox" aria-label={label} aria-expanded={open} aria-controls={id} aria-autocomplete="list" aria-activedescendant={open&&count?id+'-'+active:undefined} value={input} placeholder={allowCreate?'Найти или добавить раздел':'Найти связанное понятие'} onFocus={()=>{setOpen(true);setQuery('');setActive(0);}} onChange={e=>{setQuery(e.target.value);setOpen(true);setActive(0);}} onBlur={()=>{setOpen(false);setQuery(null);}} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setOpen(true);setActive(Math.min(active+1,count-1));}if(e.key==='ArrowUp'){e.preventDefault();setActive(Math.max(active-1,0));}if(e.key==='Escape'){setOpen(false);setQuery(null);}if(e.key==='Enter'&&open){e.preventDefault();const option=results[active];if(option)choose(option.id);else if(create)choose(input.trim());}}}/>{value&&<button type="button" className="picker-clear" aria-label={'Очистить: '+label} onMouseDown={e=>e.preventDefault()} onClick={()=>{change(undefined);setQuery(null);}}>×</button>}{open&&<div role="listbox" id={id} aria-label={label+' — результаты'} className="picker-results">{results.map((c,i)=><button type="button" role="option" aria-selected={active===i} id={id+'-'+i} key={c.id} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(c.id)}>{c.label}</button>)}{create&&<button type="button" role="option" aria-selected={active===results.length} id={id+'-'+results.length} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(input.trim())}>Создать раздел «{input.trim()}»</button>}{!count&&<p>Ничего не найдено.</p>}</div>}</div>;
}
