import { Hono } from 'hono';
import { deleteCookie, getCookie } from 'hono/cookie';
import { DomainError, object, requireScope } from '../domain/model';
import { exportGraph, turtle, namespaces } from '../domain/export';
import { digest, Store } from '../server/store';
import { accessLogin, authenticate, authorSession, issueCredential, sameOrigin, type Env } from '../server/auth';
import { Service } from '../server/service';
import { mcp } from '../server/mcp';
import { articleHtml } from '../server/html';
import { shacl } from '../domain/shacl';
const app = new Hono<{ Bindings: Env }>();
app.use('*',async (c,next) => { await next(); c.header('X-Content-Type-Options','nosniff'); c.header('Referrer-Policy','strict-origin-when-cross-origin'); c.header('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'"); if (c.req.path.startsWith('/api/') || c.req.path.startsWith('/auth/') || c.req.path === '/mcp') c.header('Cache-Control','no-store'); });
app.onError((e,c) => e instanceof DomainError ? c.json({ error:e.code,message:e.message,details:e.details },e.status as 400) : c.json({ error:'INTERNAL',message:'Операция не выполнена. Содержимое редактора сохранено.' },500));
async function body(c: Parameters<typeof authenticate>[0]) { const raw = await c.req.text(); if (raw.length>1048576) throw new DomainError('TOO_LARGE',413,'Запрос превышает 1 МБ.'); try { return JSON.parse(raw) as unknown; } catch { throw new DomainError('INVALID_JSON',400,'Некорректный JSON.'); } }
async function service(c: Parameters<typeof authenticate>[0]) { return new Service(new Store(c.env.DB),await authenticate(c)); }
app.get('/api/health',(c) => c.json({ status:'ok',stage:'working-preview',persistence:'D1',accessConfigured:!!c.env.ACCESS_AUD }));
app.get('/api/session',async (c) => { const actor = await authenticate(c); return c.json({ actor,accessConfigured:!!c.env.ACCESS_AUD }); });
app.post('/auth/session',async (c) => { sameOrigin(c); const input = await body(c); if (!object(input) || typeof input.key !== 'string' || !c.env.AUTHOR_KEY_HASH || await digest(input.key) !== c.env.AUTHOR_KEY_HASH) throw new DomainError('UNAUTHENTICATED',401,'Неверный персональный ключ.'); return c.json(await authorSession(c)); });
app.get('/auth/access',accessLogin);
app.post('/auth/logout',async (c) => { sameOrigin(c); const current=getCookie(c,'__Host-neurolex-session'); if(current)await c.env.DB.prepare('UPDATE credentials SET revoked=1 WHERE hash=?').bind(await digest(current)).run(); deleteCookie(c,'__Host-neurolex-session',{ path:'/',secure:true }); return c.json({ ok:true }); });
app.get('/api/credentials',async (c) => { const actor=await authenticate(c); requireScope(actor,'credentials'); const rows=await c.env.DB.prepare('SELECT id,actor,scopes,expires_at,revoked FROM credentials ORDER BY expires_at DESC').all(); return c.json(rows.results); });
app.post('/api/credentials',async (c) => { const actor=await authenticate(c); requireScope(actor,'credentials'); const input=await body(c); if (!object(input) || typeof input.name !== 'string' || !input.name.trim() || input.name.length>80 || !Array.isArray(input.scopes) || !input.scopes.length || input.scopes.some((s) => !['read','write','publish','schema'].includes(String(s)))) throw new DomainError('INVALID_INPUT',422,'Укажите имя и допустимые права агента.'); const credential = await issueCredential(c.env,'agent:'+input.name,input.scopes as string[],30*86400); return c.json(credential,201); });
app.delete('/api/credentials/:id',async (c) => { const actor=await authenticate(c); requireScope(actor,'credentials'); await c.env.DB.prepare('UPDATE credentials SET revoked=1 WHERE id=?').bind(c.req.param('id')).run(); return c.json({ revoked:true }); });
app.get('/api/schema',async (c) => c.json(await (await service(c)).readSchema()));
app.get('/api/articles',async (c) => c.json(await (await service(c)).list(c.req.query('q'),c.req.query('category'),c.req.query('private')==='1')));
app.get('/api/articles/:id',async (c) => c.json(await (await service(c)).read(c.req.param('id'),c.req.query('private')==='1')));
app.get('/api/articles/:id/history',async (c) => c.json(await (await service(c)).history(c.req.param('id'))));
app.post('/api/write',async (c) => c.json(await (await service(c)).mutate('write',await body(c),c.req.header('Idempotency-Key'))));
app.post('/api/restore',async (c) => c.json(await (await service(c)).mutate('restore',await body(c),c.req.header('Idempotency-Key'))));
app.post('/api/schema/preview',async (c) => c.json(await (await service(c)).preview(await body(c))));
app.post('/api/schema/apply',async (c) => c.json(await (await service(c)).mutate('schema.apply',await body(c),c.req.header('Idempotency-Key'))));
app.post('/api/import/preview',async (c) => c.json(await (await service(c)).importPreview(await body(c))));
app.post('/api/import/apply',async (c) => c.json(await (await service(c)).mutate('import',await body(c),c.req.header('Idempotency-Key'))));
app.get('/api/export',async (c) => { const svc=await service(c); const data=await svc.list('','',c.req.query('private')==='1'); return c.json({ format:'neurolex-bundle',formatVersion:1,schema:data.schema,documents:data.articles.map((a)=>a.document),corpusVersion:data.corpusVersion }); });
app.get('/api/articles/:id/export',async (c) => { const svc=await service(c); const read=await svc.read(c.req.param('id')); const document='document' in read ? read.document : read.published; if (!document) throw new DomainError('NOT_FOUND',404,'Статья не опубликована.'); const schema=(await svc.readSchema()).schema; const base=new URL(c.req.url).origin; return c.req.query('format') === 'ttl' ? c.text(await turtle(document,schema,base),200,{ 'Content-Type':'text/turtle; charset=utf-8' }) : c.json(exportGraph(document,schema,base)); });
app.post('/mcp',async (c) => { const actor=await authenticate(c); const result=await mcp(new Service(new Store(c.env.DB),actor),actor,await body(c)); return result ? c.json(result) : c.body(null,202); });
app.get('/mcp',(c) => c.json({ error:'METHOD_NOT_ALLOWED',message:'Use stateless Streamable HTTP POST with JSON-RPC. Authenticated agents use a Bearer credential.' },405));
app.get('/context/1.jsonld',(c) => c.json({ '@context':namespaces }));
app.get('/id/dictionary',(c)=>c.redirect('/',303));
app.get('/id/entry/:id/:language/:part',(c)=>c.redirect('/article/'+encodeURIComponent(c.req.param('id')),303));
app.get('/id/article/:id/*',(c)=>c.redirect('/article/'+encodeURIComponent(c.req.param('id')),303));
app.get('/id/:kind/:id', (c) => c.redirect('/article/'+encodeURIComponent(c.req.param('id')),303));
app.get('/id/entry/:id/:language', (c) => c.redirect('/article/'+encodeURIComponent(c.req.param('id')),303));
app.get('/schema.json',async(c)=>c.json((await new Service(new Store(c.env.DB),null).readSchema()).jsonSchema));
app.get('/schema.shacl.ttl',async(c)=>c.text(shacl((await new Service(new Store(c.env.DB),null).readSchema()).schema),200,{'Content-Type':'text/turtle; charset=utf-8'}));
app.get('/sitemap.xml',async(c)=>{const data=await new Service(new Store(c.env.DB),null).list();const base=new URL(c.req.url).origin;return c.text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+['/',...data.articles.map((a)=>'/article/'+a.id)].map((path)=>'<url><loc>'+base+path+'</loc></url>').join('')+'</urlset>',200,{'Content-Type':'application/xml'});});
app.get('/robots.txt',(c)=>c.text('User-agent: *\nDisallow: /api/\nDisallow: /auth/\nSitemap: '+new URL(c.req.url).origin+'/sitemap.xml\n'));
app.get('/integration',(c)=>c.html('<!doctype html><html lang="ru"><meta charset="utf-8"><title>Интеграция NeuroLex</title><body><h1>HTTP API и MCP</h1><p>Публичное чтение: GET /api/schema, GET /api/articles?q=EEG, GET /api/articles/:id.</p><p>Запись: POST /api/write с Authorization: Bearer и document, schemaVersion, expectedRevision. Текущую схему всегда получайте перед записью. Публикация требует отдельного права publish.</p><p>MCP: POST /mcp, stateless Streamable HTTP JSON-RPC. Получите schema_get перед document_write. Подключаемый клиент должен поддерживать настройку Bearer-заголовка; OAuth discovery пока не предоставляется.</p><p>Экспорт: /api/export, /api/articles/:id/export и ?format=ttl. JSON Schema: /schema.json; SHACL: /schema.shacl.ttl.</p><a href="/">Вернуться к словарю</a></body></html>'));
app.get('/vocabulary',async(c)=>{const schema=(await new Service(new Store(c.env.DB),null).readSchema()).schema;return c.json({'@context':namespaces,'@graph':schema.fields.filter((f)=>f.predicate.includes('/vocabulary#')).map((f)=>({'@id':f.predicate,'@type':namespaces.rdf+'Property',[namespaces.rdfs+'label']:f.label,[namespaces.rdfs+'comment']:f.description}))});});
app.get('/',async(c)=>articleHtml(c.env,c.req.raw,await new Service(new Store(c.env.DB),null).list()));
app.get('/article/:id',async(c)=>{const data=await new Service(new Store(c.env.DB),null).list();if(!data.articles.some((a)=>a.id===c.req.param('id'))){const shell=await c.env.ASSETS.fetch(new Request(new URL('/',c.req.url)));return new Response(await shell.text(),{status:404,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Robots-Tag':'noindex'}});}return articleHtml(c.env,c.req.raw,data,c.req.param('id'));});
app.all('/api/*' ,(c)=>c.json({ error:'NOT_FOUND' },404));
app.all('*',(c)=>c.env.ASSETS.fetch(c.req.raw));
export default app;
